##### BEGIN image/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END image/Dockerfile/image-header #####

##### BEGIN image/Dockerfile/conteco #####
COPY ./conteco/ /conteco/
RUN chmod -R +x /conteco/bin && rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END image/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
##### END image/Dockerfile/build-instructions #####

##### BEGIN image/Dockerfile/env-labels-footer #####
ENV CONTECO_TYPE="module" \
    CONTECO_NAME="schema_registry" \
    CONTECO_TAG="5.4.0" \
    CONTECO_BASE="image.wrapper" \
    CONTECO_BUILD="image"
LABEL io.vcweb.type="module" \
      io.vcweb.name="schema_registry" \
      io.vcweb.tag="5.4.0" \
      io.vcweb.base="image.wrapper" \
      io.vcweb.build="image" \
      io.vcweb.label="module.schema_registry - ContEco" \
      io.vcweb.description="Schema Registry REST module with managed standard URL." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.module.schema_registry --help"
##### END image/Dockerfile/env-labels-footer #####
