#!/usr/bin/env bash

export CONTECO_LABEL="module.schema_registry - ContEco"
export CONTECO_DESCRIPTION="Schema Registry REST module with managed standard URL."

export CONTECO_TYPE="module"
export CONTECO_NAME="schema_registry"
export CONTECO_TAG="6.0.0"

export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="image"
